import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../app/Components/Navbar/Navbar";
import Sidebar from "./Components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Diligite Keep",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} container mx-auto`}>
        <Navbar />
        <div className="pt-5 flex">
          <Sidebar />
          <div className=" sm:mx-16 px-5 ">{children}</div>
        </div>
      </body>
    </html>
  );
}
